<?php

// autoload_namespaces.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname($vendorDir);

return array(
    'System' => array($vendorDir . '/phpseclib/phpseclib/phpseclib'),
    'Prophecy\\' => array($vendorDir . '/phpspec/prophecy/src'),
    'Net' => array($vendorDir . '/phpseclib/phpseclib/phpseclib'),
    'Namshi\\JOSE' => array($vendorDir . '/namshi/jose/src'),
    'Mockery' => array($vendorDir . '/mockery/mockery/library'),
    'Math' => array($vendorDir . '/phpseclib/phpseclib/phpseclib'),
    'JakubOnderka\\PhpConsoleHighlighter' => array($vendorDir . '/jakub-onderka/php-console-highlighter/src'),
    'JakubOnderka\\PhpConsoleColor' => array($vendorDir . '/jakub-onderka/php-console-color/src'),
    'File' => array($vendorDir . '/phpseclib/phpseclib/phpseclib'),
    'Doctrine\\Common\\Inflector\\' => array($vendorDir . '/doctrine/inflector/lib'),
    'Crypt' => array($vendorDir . '/phpseclib/phpseclib/phpseclib'),
    'Cron' => array($vendorDir . '/mtdowling/cron-expression/src'),
);
